/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: polyfarm (https://sketchfab.com/polyfarm)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/female-sportswear-2-260712ec2e4d46b39b65d1e0a5a01555
title: Female Sportswear 2
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, Center, BBAnchor } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["1_Head_Mannequin_0"]: THREE.Mesh;
    Tshirt_low_Sportswear2_0: THREE.Mesh;
    ["1_Body_Mannequin_0"]: THREE.Mesh;
    Shorts_low_Sportswear2_0: THREE.Mesh;
  };
  materials: {
    Mannequin: THREE.MeshStandardMaterial;
    Sportswear2: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/female_sportswear_2/scene-transformed.glb"
  ) as any as GLTFResult;

  return (
    <group {...props} dispose={null}>
      {/* <BBAnchor anchor={[0, 1, 0]}> */}
      {/* <Center> */}
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 1587.95, -20.53]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, -22.55, -1588.43]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Head_Mannequin_0"].geometry}
                material={materials.Mannequin}
              />
            </group>
          </group>
          <group
            position={[0.12, 1218.42, -19.76]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-0.12, -19.76, -1218.42]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Tshirt_low_Sportswear2_0.geometry}
                material={materials.Sportswear2}
              />
            </group>
          </group>
          <group
            position={[0.52, 747.56, -36.86]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-0.52, -36.86, -747.56]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_Body_Mannequin_0"].geometry}
                material={materials.Mannequin}
              />
            </group>
          </group>
          <group
            position={[0.07, 902.98, -55.47]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-0.07, -55.47, -902.98]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Shorts_low_Sportswear2_0.geometry}
                material={materials.Sportswear2}
              />
            </group>
          </group>
        </group>
      </group>
      {/* </Center> */}
      {/* </BBAnchor> */}
    </group>
  );
}

useGLTF.preload("/models/female_sportswear_2/scene-transformed.glb");
