/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3dia (https://sketchfab.com/3dia)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/chest-buckle-tie-female-swimsuit-57908b6002164649a9485f2fda41ae17
title: Chest Buckle Tie Female Swimsuit
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, Center } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Swimsuit_Fabric_0: THREE.Mesh;
    Swimsuit_Metal_0: THREE.Mesh;
  };
  materials: {
    Fabric: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/chest_buckle_tie_female_swimsuit/scene.gltf"
  ) as any as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <Center>
        <group scale={1.85}>
          <group
            rotation={[Math.PI / 2, Math.PI / 2, Math.PI / 1]}
            scale={0.01}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Swimsuit_Fabric_0.geometry}
              material={materials.Fabric}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Swimsuit_Metal_0.geometry}
              material={materials.Metal}
            />
          </group>
        </group>
      </Center>
    </group>
  );
}

useGLTF.preload("/models/chest_buckle_tie_female_swimsuit/scene.gltf");
