/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3dia (https://sketchfab.com/3dia)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/female-over-bikini-twin-strap-top-abea90d38c6a4e28a31abd3f436f2149
title: Female Over Bikini Twin Strap Top
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Top_fabric_0: THREE.Mesh;
  };
  materials: {
    fabric: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/scene.gltf") as any as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.63}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Top_fabric_0.geometry}
            material={materials.fabric}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
