/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3dia (https://sketchfab.com/3dia)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/female-halter-neck-black-bikini-top-78742ffe18a04114989addca6e699202
title: Female Halter Neck Black Bikini Top
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bikin_Top_Fabric_0: THREE.Mesh;
  };
  materials: {
    Fabric: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/female_halter_neck_black_bikini_top/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.53}
      >
        <group
          name="5096371176c94214ba5c5660d7582a27fbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Bikin_Top_Fabric_0"
            castShadow
            receiveShadow
            geometry={nodes.Bikin_Top_Fabric_0.geometry}
            material={materials.Fabric}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
