/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3dia (https://sketchfab.com/3dia)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/female-corded-two-piece-bikini-set-e171bca33ef44107a11f954615685ff2
title: Female Corded Two Piece Bikini Set
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BikiniSet_Fabric_0: THREE.Mesh;
  };
  materials: {
    Fabric: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/female_corded_two_piece_bikini_set/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BikiniSet_Fabric_0.geometry}
            material={materials.Fabric}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
