/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3dia (https://sketchfab.com/3dia)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/fringe-bandeau-bikini-two-piece-bikini-set-a136697bc72845d3bc540794a4aba587
title: Fringe Bandeau Bikini Two Piece Bikini Set
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    FringesBikiniSet_BikiniMaterial_0: THREE.Mesh;
  };
  materials: {
    BikiniMaterial: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/fringe_bandeau_bikini_two_piece_bikini_set/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.11}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.FringesBikiniSet_BikiniMaterial_0.geometry}
            material={materials.BikiniMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
